Document: pipexec
Title: Debian pipexec Manual
Author: <insert document author here>
Abstract: This manual describes what pipexec is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pipexec/pipexec.sgml.gz

Format: postscript
Files: /usr/share/doc/pipexec/pipexec.ps.gz

Format: text
Files: /usr/share/doc/pipexec/pipexec.text.gz

Format: HTML
Index: /usr/share/doc/pipexec/html/index.html
Files: /usr/share/doc/pipexec/html/*.html
