---

name: CompileCheck

on: [push]

jobs:
  compile:
    name: ${{ matrix.cenv.runs-on }}-${{ matrix.cenv.cc }}
    strategy:
      matrix:
        cenv:
          - { runs-on: ubuntu-20.04, cc: gcc-9, pkg: gcc-9 }
          - { runs-on: ubuntu-20.04, cc: gcc-10, pkg: gcc-10 }
          - { runs-on: ubuntu-20.04, cc: i686-linux-gnu-gcc-9, pkg: gcc-9-i686-linux-gnu }
          - { runs-on: ubuntu-20.04, cc: i686-linux-gnu-gcc-10, pkg: gcc-10-i686-linux-gnu }
          - { runs-on: ubuntu-20.04, cc: clang-10, pkg: clang-10 }
          - { runs-on: ubuntu-20.04, cc: clang-11, pkg: clang-11 }
          - { runs-on: ubuntu-20.04, cc: clang-12, pkg: clang-12 }
          - { runs-on: ubuntu-22.04, cc: gcc-9, pkg: gcc-9 }
          - { runs-on: ubuntu-22.04, cc: gcc-10, pkg: gcc-10 }
          - { runs-on: ubuntu-22.04, cc: gcc-11, pkg: gcc-11 }
          - { runs-on: ubuntu-22.04, cc: gcc-12, pkg: gcc-12 }
          - { runs-on: ubuntu-22.04, cc: i686-linux-gnu-gcc-9, pkg: gcc-9-i686-linux-gnu }
          - { runs-on: ubuntu-22.04, cc: i686-linux-gnu-gcc-10, pkg: gcc-10-i686-linux-gnu }
          - { runs-on: ubuntu-22.04, cc: i686-linux-gnu-gcc-11, pkg: gcc-11-i686-linux-gnu }
          - { runs-on: ubuntu-22.04, cc: i686-linux-gnu-gcc-12, pkg: gcc-12-i686-linux-gnu }
          - { runs-on: ubuntu-22.04, cc: clang-12, pkg: clang-12 }
          - { runs-on: ubuntu-22.04, cc: clang-13, pkg: clang-13 }
          - { runs-on: ubuntu-22.04, cc: clang-14, pkg: clang-14 }
          - { runs-on: ubuntu-24.04, cc: gcc-12, pkg: gcc-12 }
          - { runs-on: ubuntu-24.04, cc: gcc-13, pkg: gcc-13 }
          - { runs-on: ubuntu-24.04, cc: gcc-14, pkg: gcc-14 }
          - { runs-on: ubuntu-24.04, cc: i686-linux-gnu-gcc-12, pkg: gcc-12-i686-linux-gnu }
          - { runs-on: ubuntu-24.04, cc: i686-linux-gnu-gcc-13, pkg: gcc-13-i686-linux-gnu }
          - { runs-on: ubuntu-24.04, cc: i686-linux-gnu-gcc-14, pkg: gcc-14-i686-linux-gnu }
          - { runs-on: ubuntu-24.04, cc: clang-16, pkg: clang-16 }
          - { runs-on: ubuntu-24.04, cc: clang-17, pkg: clang-17 }
          - { runs-on: ubuntu-24.04, cc: clang-18, pkg: clang-18 }
    runs-on: ${{ matrix.cenv.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          # This is needed as the version.sh script uses
          # the history.
          fetch-depth: 0
      - name: "Install compiler - should in most cases be a noop"
        run: sudo apt-get install -y ${{ matrix.cenv.pkg }}
      - run: |
          bash -x build/init_autotools.sh
          mkdir -p COMPILE
          cd COMPILE
          CC=${{ matrix.cenv.cc }} ../configure
          make
          bash ../test/basic_tests.sh
        shell: bash
